import Head from "next/head";
import Link from "next/link";

import AppBar from "../components/AppBar";
import Hero from "../components/Hero";



export default function Home() {


  return (
    <div className="w-screen h-screen">
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar/>
      <div className="container m-auto w-full bg-gray-300 h-screen">
      <Hero/>
      </div>
    </div>
  );
}
