import Head from "next/head";
import Link from "next/link";

import AppBar from "../components/AppBar";
import Hero from "../components/Hero";
import Footer from "../components/Footer";



export default function Home() {


  return (
    <div className="w-screen h-full">
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar/>
      <div className="shadow-2xl container m-auto w-full bg-gray-300 h-full 2xl:h-screen">
      <Hero/>   
      </div>
      <Footer/>
    </div>
  );
}
